name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      run: npm install

    - name: Code linter
      run: $(npm bin)/grunt lint

    - name: Tests
      run: $(npm bin)/nyc --reporter=html node tests/all-tests.js
